{% set name = "xcube-sh" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-sh/archive/v{{ version }}.tar.gz
  sha256: 7775da6b388226e4f890d064e97ead5bc5ba47004e7dae9f688fd281ccafc2cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - xcube >=0.8.0
    - oauthlib >=3.0
    - requests-oauthlib >=1.3

test:
  imports:
    - xcube_sh

about:
  summary: xcube plugin for the Sentinel Hub Cloud API
  home: https://github.com/dcs4cop/xcube-sh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-sh is an xcube plugin that allows generating data cubes from the Sentinel Hub Cloud API.
  doc_url: https://github.com/dcs4cop/xcube-sh/blob/master/README.md
  dev_url: https://github.com/dcs4cop/xcube-sh

extra:
  recipe-maintainers:
    - pont-us
    - dzelge
    - TonioF
    - forman
    - AliceBalfanz
