{% set name = "xcube-sh" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-sh/archive/v{{ version }}.tar.gz
  sha256: b0243d0b9e966992f64469bf0f31a93870b459af9bba9bf8056b1d4309577937

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - numcodecs
    - numpy
    - oauthlib >=3.0
    - pandas
    - psutil
    - pyproj
    - requests
    - requests-oauthlib >=1.3
    - xarray
    - xcube >=0.10
    - zarr

test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube_sh

about:
  summary: xcube plugin for the Sentinel Hub Cloud API
  home: https://github.com/xcube-dev/xcube-sh
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-sh is an xcube plugin that allows generating data cubes from the Sentinel Hub Cloud API.
  doc_url: https://github.com/xcube-dev/xcube-sh/blob/main/README.md
  dev_url: https://github.com/xcube-dev/xcube-sh

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - forman
    - konstntokas
    - pont-us
    - ruchimotwaniBC
    - TejasMorbagal
    - thomasstorm
    - TonioF
